name: Push

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare tag name from Release Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set tag and image outputs (backend)
        id: set_tag
        run: |
          test -n "${TAG}" || TAG=temp-${GITHUB_SHA::8}-$(date +%s)
          IMAGE="ghcr.io/${GITHUB_REPOSITORY}"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}

      - name: Set up Docker buildX
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Build image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          pull: true
          load: true
          tags: ${{ steps.set_tag.outputs.tagged_image }}

      - name: Push image
        run: docker push ${{ steps.set_tag.outputs.tagged_image }}